const items = [
    // Men Fashion Items
    {
        id: 1,
        category: 'Men',
        title: "Solid Men Black Track Pants",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/jyyqc280/track-pant/p/g/s/m-41864black-wildcraft-original-imafj3h4zh8rgjzt.jpeg?q=50',
        description: 'Wildcraft, Original Price: 1,599, Discount: 38% off',
        price: '989',
        date: '2024-08-13',
    },
    {
        id: 2,
        category: 'Men',
        title: "Men Printed Casual Shirt",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k2z1t3k0/shirt/n/b/e/40-lrsfcslf143317-louis-philippe-jeans-original-imafm7gjzjaahtxc.jpeg?q=50',
        description: 'Louis Philippe Jeans, Original Price: 1,899, Discount: 15% off',
        price: '1,614',
        date: '2024-08-13',
    },
    {
        id: 3,
        category: 'Men',
        title: "Men & Women Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k6i7zww0/sock/y/w/f/free-ad-sole-1-pkt-adidas-original-imafz7yxcfkyvrcg.jpeg?q=50',
        description: 'ADIDAS, Original Price: 439, Discount: 59% off',
        price: '177',
        date: '2024-08-13',
    },
    {
        id: 4,
        category: 'Men',
        title: "Men & Women Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k2z1t3k0/sock/x/n/s/free-f-asst-1-jockey-original-imafm7ajuavkdsbq.jpeg?q=50',
        description: 'Jockey, Original Price: 449, Discount: 55% off',
        price: '199',
        date: '2024-08-13',
    },
    {
        id: 5,
        category: 'Men',
        title: "Men & Women Color Block Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/ju2z6a80/sock/b/q/r/free-37-appalon-original-imaff9cf7hztztef.jpeg?q=50',
        description: 'APPALON, Original Price: 599, Discount: 62% off',
        price: '223',
        date: '2024-08-13',
    },
    {
        id: 6,
        category: 'Men',
        title: "Men & Women Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k6i7zww0/sock/z/d/f/free-ankle-length-prahard-original-imafmz2c8mz92vpp.jpeg?q=50',
        description: 'PRAHARD, Original Price: 699, Discount: 64% off',
        price: '248',
        date: '2024-08-13',
    },
    {
        id: 7,
        category: 'Men',
        title: "Men & Women Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/jfzpuvk0/sock/z/k/t/free-adigrs-99-adidas-original-imaf4cfnp4sqtagu.jpeg?q=50',
        description: 'ADIDAS, Original Price: 490, Discount: 60% off',
        price: '196',
        date: '2024-08-13',
    },
    {
        id: 8,
        category: 'Men',
        title: "Men Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/jdvziq80/sock/t/t/2/free-puma-sher3-puma-original-imaf2zvfav3yaf8t.jpeg?q=50',
        description: 'Puma, Original Price: 999, Discount: 68% off',
        price: '312',
        date: '2024-08-13',
    },

    // Women Fashion Items
    {
        id: 9,
        category: 'Women',
        title: "T-Shirt And Shorts",
        imgSrc: 'https://m.media-amazon.com/images/I/71HOdqyApyL._SX679_.jpg',
        description: 'Fabric:- Soft',
        price: '999',
        date: '2024-08-13',
    },
    {
        id: 10,
        category: 'Women',
        title: "T-Shirt And Shorts",
        imgSrc: 'https://m.media-amazon.com/images/I/71fZUdH2IAL._SX679_.jpg',
        description: 'Fabric:- Soft',
        price: '999',
        date: '2024-08-13',
    },
    {
        id: 11,
        category: 'Women',
        title: "Oversized T-Shirt",
        imgSrc: 'https://th.bing.com/th/id/OIP.-lwIdwOgD85Ettu6GHCbNAHaHa?rs=1&pid=ImgDetMain',
        description: 'Cotton Blend, printed',
        price: '999',
        date: '2024-08-13',
    },
    {
        id: 12,
        category: 'Women',
        title: "Slipper Sandals",
        imgSrc: 'https://m.media-amazon.com/images/I/51Sy5353soL._SY695_.jpg',
        description: 'Skin Friendly Material',
        price: '999',
        date: '2024-08-13',
    },
    {
        id: 13,
        category: 'Women',
        title: "Sneakers",
        imgSrc: 'https://m.media-amazon.com/images/I/71iwpAqaDOL._SY695_.jpg',
        description: 'Running Shoe, comfortable',
        price: '19999',
        date: '2024-08-13',
    },
    {
        id: 14,
        category: 'Women',
        title: "Slippers",
        imgSrc: 'https://m.media-amazon.com/images/I/51-2tM1l6rL._SX695_.jpg',
        description: 'Skin Friendly Material',
        price: '69999',
        date: '2024-08-13',
    },
    {
        id: 15,
        category: 'Women',
        title: "T-Shirt And Shorts",
        imgSrc: 'https://m.media-amazon.com/images/I/71HOdqyApyL._SX679_.jpg',
        description: 'Fabric:- Soft',
        price: '999',
        date: '2024-08-13',
    },
    {
        id: 16,
        category: 'Women',
        title: "T-Shirt And Shorts",
        imgSrc: 'https://m.media-amazon.com/images/I/71fZUdH2IAL._SX679_.jpg',
        description: 'Fabric:- Soft',
        price: '999',
        date: '2024-08-13',
    },
    {
        id: 17,
        category: 'Women',
        title: "Oversized T-Shirt",
        imgSrc: 'https://th.bing.com/th/id/OIP.-lwIdwOgD85Ettu6GHCbNAHaHa?rs=1&pid=ImgDetMain',
        description: 'Cotton Blend, printed',
        price: '999',
        date: '2024-08-13',
    },

    // Footwear Items
    {
        id: 18,
        category: 'Footwear',
        title: "Track V2 IDP Running Shoes For Women",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k5lcvbk0/shoe/f/k/g/372482-9-puma-royal-white-original-imafgb4nn6dexgmw.jpeg?q=50',
        description: 'Puma, Original Price: 3,999, Discount: 50% off',
        price: '1,999',
        date: '2024-08-13',
    },
    {
        id: 19,
        category: 'Footwear',
        title: "Dwane Slip-On IDP Running Shoes For Women",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k70spzk0/shoe/b/f/z/193332-7-puma-pink-glimmer-silver-original-imafpcu2dxjcwcn4.jpeg?q=50',
        description: 'Puma, Original Price: 3,799, Discount: 60% off',
        price: '1,519',
        date: '2024-08-13',
    },
    {
        id: 20,
        category: 'Footwear',
        title: "Women Beige Flats Sandal",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/sandal/d/n/y/beige-rsnch-3152pe-footrendz-37-original-imaefgnm93a8evag.jpeg?q=50',
        description: 'Footrendz, Original Price: 549, Discount: 48% off',
        price: '284',
        date: '2024-08-13',
    },
    {
        id: 21,
        category: 'Footwear',
        title: "Combo Pack of 4 Latest Collection Stylish Casual Sneaker",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k5jxfgw0/shoe/k/q/4/combo-4-993-767-1044-766-8-tying-multicolor-original-imafz6qnzftswvyz.jpeg?q=50',
        description: 'Shoefly, Original Price: 1,996, Discount: 53% off',
        price: '929',
        date: '2024-08-13',
    },
    {
        id: 22,
        category: 'Footwear',
        title: "Extra Soft Slippers For Women Slippers",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k1nw9zk0/slipper-flip-flop/9/k/8/bluecombo-001-7-doctor-extra-soft-blue-original-imafksyfzwwxjdrz.jpeg?q=50',
        description: 'DOCTOR EXTRA SOFT, Original Price: 599, Discount: 39% off',
        price: '360',
        date: '2024-08-13',
    },
    {
        id: 23,
        category: 'Footwear',
        title: "Slippers",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k47cgi80/slipper-flip-flop/d/v/s/blackpinkcombo-001-10-doctor-extra-soft-blackpink-original-imafn5jdzzcznzgv.jpeg?q=50',
        description: 'DOCTOR EXTRA SOFT, Original Price: 599, Discount: 39% off',
        price: '360',
        date: '2024-08-13',
    },
    {
        id: 24,
        category: 'Footwear',
        title: "Combo Pack Of 2 Pairs Of Women Slippers",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k4k7f680/slipper-flip-flop/z/s/s/bls003-bls004-001-4-beonza-multicolor-original-imafnfvhmhg6h66e.jpeg?q=50',
        description: 'Beonza, Original Price: 999, Discount: 70% off',
        price: '299',
        date: '2024-08-13',
    },
    {
        id: 25,
        category: 'Footwear',
        title: "Women Black Flats Sandal",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k4n2avk0/sandal/g/m/z/f010-4-gibelle-black-original-imafbh6znpuqqvsp.jpeg?q=50',
        description: 'GIBELLE, Original Price: 699, Discount: 44% off',
        price: '389',
        date: '2024-08-13',
    },
    {
        id: 26,
        category: 'Footwear',
        title: "Women SFL-504 Navy Blue Flip Flops",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k2nmaa80/slipper-flip-flop/v/v/2/sf0504l-6-sparx-navyblue-original-imaf7wmfzrwwyr5v.jpeg?q=50',
        description: 'Sparx, Original Price: 274, Discount: 15% off',
        price: '232',
        date: '2024-08-13',
    },

    // Laptop Items
    {
        id: 27,
        category: 'Electronics',
        title: "Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/Linux) Inspiron 3481 Laptop",
        imgSrc: 'https://example.com/dell-laptop.jpg', // Add an appropriate image URL
        description: 'Price: 26,990, Original Price: 29,575, Discount: 8% off, Rating: 4.1',
        price: '26,990',
        originalPrice: '29,575',
        discountRate: '8% off',
        rating: '4.1',
        date: '2024-08-13',
    },
    {
        id: 28,
        category: 'Electronics',
        title: "HP Pavilion Core i5 9th Gen - (8 GB/1 TB HDD/Windows 10 Home/3 GB Graphics/NVIDIA Geforce GTX 1050) 15",
        imgSrc: 'https://example.com/hp-pavilion.jpg', // Add an appropriate image URL
        description: 'Price: 52,990, Original Price: 66,041, Discount: 19% off, Rating: 4.2',
        price: '52,990',
        originalPrice: '66,041',
        discountRate: '19% off',
        rating: '4.2',
        date: '2024-08-13',
    },
    {
        id: 29,
        category: 'Electronics',
        title: "HP 15s Ryzen 3 Dual Core - (4 GB/256 GB SSD/Windows 10 Home) 15s-eq0007AU Thin and Light Laptop",
        imgSrc: 'https://example.com/hp-15s.jpg', // Add an appropriate image URL
        description: 'Price: 30,990, Original Price: 32,598, Discount: 4% off, Rating: 4.5',
        price: '30,990',
        originalPrice: '32,598',
        discountRate: '4% off',
        rating: '4.5',
        date: '2024-08-13',
    },
    {
        id: 30,
        category: 'Electronics',
        title: "HP 15 Pentium Gold - (4 GB/1 TB HDD/Windows 10 Home) 15-di0001TU Laptop",
        imgSrc: 'https://example.com/hp-15-pentium.jpg', // Add an appropriate image URL
        description: 'Price: 24,990, Original Price: 25,556, Discount: 2% off, Rating: 4.4',
        price: '24,990',
        originalPrice: '25,556',
        discountRate: '2% off',
        rating: '4.4',
        date: '2024-08-13',
    },
    {
        id: 31,
        category: 'Electronics',
        title: "Lenovo Ideapad S145 APU Dual Core A6 - (4 GB/1 TB HDD/Windows 10 Home) S145-15AST Thin and Light Laptop",
        imgSrc: 'https://example.com/lenovo-ideapad.jpg', // Add an appropriate image URL
        description: 'Price: 20,990, Original Price: 22,392, Discount: 6% off, Rating: 4',
        price: '20,990',
        originalPrice: '22,392',
        discountRate: '6% off',
        rating: '4',
        date: '2024-08-13',
    },
    {
        id: 32,
        category: 'Electronics',
        title: "Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 TB HDD/Windows 10 Home) 130-15IKB Laptop",
        imgSrc: 'https://example.com/lenovo-ideapad-130.jpg', // Add an appropriate image URL
        description: 'Price: 28,990, Original Price: 33,040, Discount: 12% off, Rating: 4',
        price: '28,990',
        originalPrice: '33,040',
        discountRate: '12% off',
        rating: '4',
        date: '2024-08-13',
    },
    {
        id: 33,
        category: 'Electronics',
        title: "Acer Nitro 5 Core i7 9th Gen - (8 GB/1 TB HDD/256 GB SSD/Windows 10 Home/4 GB Graphics/NVIDIA Geforce GTX 1650)",
        imgSrc: 'https://example.com/acer-nitro-5.jpg', // Add an appropriate image URL
        description: 'Price: 69,990, Original Price: 1,04,999, Discount: 33% off, Rating: 4.6',
        price: '69,990',
        originalPrice: '1,04,999',
        discountRate: '33% off',
        rating: '4.6',
        date: '2024-08-13',
    },
    {
        id: 34,
        category: 'Electronics',
        title: "HP Pavilion x360 Core i3 8th Gen - (4 GB/256 GB SSD/Windows 10 Home) 14-dh0107TU 2 in 1 Laptop",
        imgSrc: 'https://example.com/hp-pavilion-x360.jpg', // Add an appropriate image URL
        description: 'Price: 42,990, Original Price: 45,391, Discount: 5% off, Rating: 4.5',
        price: '42,990',
        originalPrice: '45,391',
        discountRate: '5% off',
        rating: '4.5',
        date: '2024-08-13',
    },
    {
        id: 35,
        category: 'Electronics',
        title: "Asus ZenBook Core i5 8th Gen - (8 GB/256 GB SSD/Windows 10 Home) UX430UA-GV573T Thin and Light Laptop",
        imgSrc: 'https://example.com/asus-zenbook.jpg', // Add an appropriate image URL
        description: 'Price: 45,990, Original Price: 86,990, Discount: 47% off, Rating: 4.2',
        price: '45,990',
        originalPrice: '86,990',
        discountRate: '47% off',
        rating: '4.2',
        date: '2024-08-13',
    },
];

module.exports = items;
