const items = [
    {
        id: 1,
        category: 'Men Fashion',
        title: "Solid Men Black Track Pants",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/jyyqc280/track-pant/p/g/s/m-41864black-wildcraft-original-imafj3h4zh8rgjzt.jpeg?q=50',
        description: 'Wildcraft, Original Price: 1,599, Discount: 38% off',
        price: '989',
        date: '2024-08-13',
    },
    {
        id: 2,
        category: 'Men Fashion',
        title: "Men Printed Casual Shirt",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k2z1t3k0/shirt/n/b/e/40-lrsfcslf143317-louis-philippe-jeans-original-imafm7gjzjaahtxc.jpeg?q=50',
        description: 'Louis Philippe Jeans, Original Price: 1,899, Discount: 15% off',
        price: '1,614',
        date: '2024-08-13',
    },
    {
        id: 3,
        category: 'Men & Women Fashion',
        title: "Men & Women Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k6i7zww0/sock/y/w/f/free-ad-sole-1-pkt-adidas-original-imafz7yxcfkyvrcg.jpeg?q=50',
        description: 'ADIDAS, Original Price: 439, Discount: 59% off',
        price: '177',
        date: '2024-08-13',
    },
    {
        id: 4,
        category: 'Men & Women Fashion',
        title: "Men & Women Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k2z1t3k0/sock/x/n/s/free-f-asst-1-jockey-original-imafm7ajuavkdsbq.jpeg?q=50',
        description: 'Jockey, Original Price: 449, Discount: 55% off',
        price: '199',
        date: '2024-08-13',
    },
    {
        id: 5,
        category: 'Men & Women Fashion',
        title: "Men & Women Color Block Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/ju2z6a80/sock/b/q/r/free-37-appalon-original-imaff9cf7hztztef.jpeg?q=50',
        description: 'APPALON, Original Price: 599, Discount: 62% off',
        price: '223',
        date: '2024-08-13',
    },
    {
        id: 6,
        category: 'Men & Women Fashion',
        title: "Men & Women Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/k6i7zww0/sock/z/d/f/free-ankle-length-prahard-original-imafmz2c8mz92vpp.jpeg?q=50',
        description: 'PRAHARD, Original Price: 699, Discount: 64% off',
        price: '248',
        date: '2024-08-13',
    },
    {
        id: 7,
        category: 'Men & Women Fashion',
        title: "Men & Women Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/jfzpuvk0/sock/z/k/t/free-adigrs-99-adidas-original-imaf4cfnp4sqtagu.jpeg?q=50',
        description: 'ADIDAS, Original Price: 490, Discount: 60% off',
        price: '196',
        date: '2024-08-13',
    },
    {
        id: 8,
        category: 'Men Fashion',
        title: "Men Solid Ankle Length",
        imgSrc: 'https://rukminim1.flixcart.com/image/329/395/jdvziq80/sock/t/t/2/free-puma-sher3-puma-original-imaf2zvfav3yaf8t.jpeg?q=50',
        description: 'Puma, Original Price: 999, Discount: 68% off',
        price: '312',
        date: '2024-08-13',
    },
];

module.exports = items;
